# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-11-14 09:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171114_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetails',
            old_name='product',
            new_name='cproduct',
        ),
        migrations.RenameField(
            model_name='cartdetails',
            old_name='user',
            new_name='cuser',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 14, 14, 46, 30, 140387)),
        ),
    ]
