# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-11-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phoneno',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
